config/routes.rb
ControlRequest::Application.routes.draw do

  root 'welcome#index'

  

  resources :users 
  resources :clients do
    resources :requests
  end

  match "/clients/:name" => 'requests#index_requests', :via => :get, :as => :index_requests
end

app/models/client.rb
class Client < ActiveRecord::Base

	# attributes and validations
	
	validates :description, :presence => true, :allow_blank => false, :length => {:minimum => 5, :maximum => 50}
	validates :adress, :presence => true, :allow_blank => false

	# associations
	belongs_to :user

	has_many :requests

end

app/models/request.rb
class Request < ActiveRecord::Base

	# attributes and validations
	validates :description, :presence => :true, :allow_blank => false
	validates :status, :presence => true
	validates :client_id, :presence => true

	# associations
	belongs_to :client
end

app/models/status.rb
class Status < ActiveRecord::Base

	# attribute
	validates :description, :presence => true
end

app/models/user.rb
class User < ActiveRecord::Base

	# attributes and validations
	validates :name, :presence => true, :allow_blank => false, :length => {:minimum => 5, :maximum => 50}
	validates :email, :presence => true, :allow_blank => false, :fomat => {:with => /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\Z/i, :on => :create}

	# associations
	has_many :clients

	def send_email
		AppMailer::UserMailer.welcome_message(self.name, self.email).deliver
	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/clients_controller.rb
# -*- coding: utf-8 -*-
class ClientsController < ApplicationController

	before_action :set_client, :only => [:show, :edit, :update, :destroy]


	def index
		@clients = Client.all
	end

	def new
		@client = Client.new
	end

	def create
		@client = Client.new(client_params)

		if @client.save
			flash[:notice] = "Cliente cadastrado com sucesso!!"
			redirect_to clients_path
		else
			flash[:notice] = "Algum campo está faltando ou os dados foram ineridos incorretamente!"
			render :action => :new
		end
	end

	def show
	end

	def edit
	end

	def update

		if @client.update(client_params)
			flash[:notice] = "Cliente atualizado com sucesso!"
			redirect_to @client
		else
			flash[:notice] = "Dados alterados incorretamente!"
			render :action => :edit
		end

	end

	def destroy
		flash[:notice] = @client.destroy ? "Cliente excluído com sucesso!" : "Não foi possível excluir esse cliente!"
		redirect_to clients_path
	end

	private 
	def set_client
		@client = Client.find(params[:id])
	end

	def client_params
		params.require(:client).permit(:description, :adress)
	end
end

app/controllers/requests_controller.rb
class RequestsController < ApplicationController

	before_action :set_request, :only => [:show, :edit, :update, :destroy]
	
	def index
		@client = Client.where(:id => params[:client_id])
		@requests = @client.requests
	end

	def index_requests
		if params[:name]
			@client = Client.where(:description => params[:name]).first
			@requests = @client.requests
		else
			@requests = Request.all
		end
	end

	def new

	end

	def new_request
		@request = Request.new
	end

	def create
		@request = Request.new(request_params)
		
		if @request.save
			flash[:notice] = "Requisicao inserida com sucesso!"
		else
			flash[:notice] = "Erro ao inserir requisicao"
		end
	end

	def show 
	end

	def edit
	end

	def update
		flash[:notice] = @request.update_attributes(request_params) ? "Requisicao alterada com sucesso" : "Erro ao modificar requisicao"
	end

	def destroy
		flash[:notice] = @request.destroy ? "Requisicao excluida com sucesso!" : "Erro ao inserir requisicao"
	end

	private
	def set_request
		@request = Request.find(params[:id])	
	end

	def request_params
		params.require(:request).permit(:description, :status, :client_id)
	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'Usuario foi gravado com sucesso!' }
        format.json { render action: 'show', status: :created, location: @user }
      else
        format.html { render action: 'new' }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'Usuario foi atualizado com sucesso!' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:name, :email, :login)
    end

    
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

	def index
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
	def bootstrap_alert(type)
		html = <<-HTML 
		<div class="alert #{type}">
			<button type="button" class="close" data-dismiss="alert">&times;</button>
			#{notice}
		</div>
		HTML
		html.html_safe
	end
end

app/helpers/clients_helper.rb
module ClientsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/clients/_form.html.erb
<%=form_for(client) do |f| %>
<div class="control-group">
	<%=f.label :description, "Descrição:"%>
	<div class="controls">
		<%=f.text_field :description, :class => "input-xlarge"%>
	</div>
</div>

<div class="control-group">
	<%=f.label :adress, "Endereço:", :class => "control-label"%>
	<div class="controls">
		<%=f.text_area :adress, :class => "input-xlarge"%>
	</div>
</div>

<div>
	<%=f.submit "Salvar", :class => "btn btn-success"%>
	<%=link_to "Voltar", clients_path, :class => "btn" %>
</div>

<% end %>

app/views/clients/edit.html.erb
  <div class="row-fluid">
  	<div class="page-header">
  		<h1>Cliente <small>Editando cliente</small></h1>
  	</div>
  		<%=render :partial => 'form', :locals => {:client => @client} %>
  </div>

app/views/clients/index.html.erb
<div class="row-fluid">
	<div class="alert alert-info">
			<button type="button" class="close" data-dismiss="alert">&times;</button>
			<%= notice %>
		</div>
	<div class="page-header">
		<h1>Clientes</h1>
	</div>

	<table class="table table-striped table-bordered table-condensed">
		<thead>
			<tr>
				<th>ID</th>
				<th>Descrição</th>
				<th>Endereço</th>
				<th></th>
			</tr>

		</thead>
		<tbody>
			<% if @clients.any? %>
			<% @clients.each do |client| %>
			<tr class="list-users">
				<td><%=client.id %></td>
				<td><%=client.description %></td>
				<td><%=client.adress %></td>
				<td>
					<div class="btn-group">
						<a class="btn btn-mini dropdown-toggle" data-toggle="dropdown" href="#">Actions <span class="caret"></span></a>
						<ul class="dropdown-menu">
							<li><%=link_to fa_icon("pencil")+" Editar", edit_client_path(client)%></li>
							<li><%=link_to fa_icon("globe")+" Requsições", index_requests_path(client.description) %></li>
							<li><%=link_to fa_icon("trash-o")+" Deletar", client, :method => :delete, :confirm => "Você tem certeza?" %></li>
							<li><%=link_to fa_icon("user")+" Detalhes", client %></li>
						</ul>
					</div>
				</td>

			</tr>
			<% end %>

			<% else %>
			<div class="alert">
				Não há clientes cadastrados
			</div>
			<% end %>
		</tbody>
	</table>	
	</div>
</div>

app/views/clients/new.html.erb
  <div class="row-fluid">
  	<div class="page-header">
  		<h1>Novo Cliente <small>Adicionar novo cliente</small></h1>
  	</div>
  		<%=render :partial => 'form', :locals => {:client => @client} %>
  </div>

app/views/clients/show.html.erb
  <div id="notice">
    <%=notice %>
  </div>
  <div class="row-fluid">
  	<div class="page-header">
  		<h1>Detalhes do cliente</h1>
  	</br>
  		<table class="table table-striped table-bordered table-condensed">
  			<tr>
  				<h2><p><b>Descrição: </b> <%=@client.description %></p></h3>
  				<h4><p><b>Endereço: </b> <%=@client.adress %></p></h4>
  			</tr>
  		</table>

      <div id="nova_requisicao">
        <%=render :partial => 'requests/form', :locals => {:request => Request.new, :client => @client} %>

      </div>

      <div id="requisicao">
        <%=render :partial => 'requests/index', :locals => {:requests => @client.requests} %>
      </div>

  		<%=link_to "Editar ", edit_client_path(@client), :class => "btn btn-primary" %>
  		<%=link_to "Voltar ", clients_path, :class => "btn" %>
  </div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
	<title>ControlRequest</title>
	<%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
	<%= javascript_include_tag "application", "data-turbolinks-track" => true %>
	<%= csrf_meta_tags %>
</head>
<body>
	<%=render :partial => 'shared/menu_top' %>

	<div class="container-fluid">
		<div class="row-fluid">


			<%=render :partial => 'shared/sidebar' %>


			<div class="span9">
				<%= yield %>

				<script type="text/javascript">
				$(document).ready(function() {
					$('.dropdown-menu li a').hover(
						function() {
							$(this).children('i').addClass('icon-white');
						},
						function() {
							$(this).children('i').removeClass('icon-white');
						});

					if($(window).width() > 760)
					{
						$('tr.list-users td div ul').addClass('pull-right');
					}
				});
				</script>

			</div>

		</div>
	</div>

</body>
</html>

app/views/requests/_form.html.erb
<h4>Requisição</h4>

<%=form_for([client,request], :remote => true) do |f|%>
	
	<%=f.hidden_field :client_id, :value => client.id %>
	<div class="field">
		<%=f.label :description, "Descrição: " %>
		<%=f.text_field :description %>
	</div>

	<div class="field">
		<%=f.label :status, "Status: " %>
		<%=f.select :status, options_for_select(Status.all.collect {|s| [s.description, s.description]}) %>
	</div>

	<div class="actions">
		<%=f.submit "Salvar", :class => "btn btn-success" %>
	</div>
<% end %>

app/views/requests/_index.html.erb
<hr>
<h4>Requisições</h4>

<% if requests.any? %>
<% requests.each do |request| %>
<div id="request_<%=request.id %>" class="well well-small"%>
	<table>
		<tr class="list-users">

			<td><h4><%=request.description %></h4></td>
			<td><h5><%=request.status %></h5></td>
			
			<td><%=link_to "Editar", edit_client_request_path(request.client, request), :class => "btn btn-primary", :remote => true %></td>

		</tr>
	</table>
</div>
</br>

<% end %>
<% else %>
</br>
<div class="alert">
	Não requisições solicitadas pelo cliente selecionado
</div>

<% end %>

app/views/requests/create.js.erb
<% if @request.persisted? %>
$("#requisicao").html("<%=j render :partial => 'requests/index', :locals => {:requests => @request.client.requests} %>");
$("#requisicao").prepend("<%=j notice %>");
$("#nova_requisicao").html("<%=j render :partial => 'requests/form', :locals => {:request => Request.new, :client => @request.client} %>");
<% else %>
$("#nova_requisicao").html("<%=j render :partial => 'request/form', :locals => {:request => @request, :client => @request.client} %>");

app/views/requests/destroy.js.erb
<% if @request.destroyed? %>
$("#request_<%=request.id %>").remove();
<% else %>
$("#request_<%=request.id %>").prepend("<%= Erro ao escluir requisicao %>");
<% end %>

app/views/requests/index_requests.html.erb
<div class="row-fluid">
	<div class="alert alert-info">
			<button type="button" class="close" data-dismiss="alert">&times;</button>
			<%= notice %>
		</div>
	<div class="page-header">
		<h1>Clientes</h1>
	</div>

	<table class="table table-striped table-bordered table-condensed">
		<thead>
			<tr>
				<th>ID</th>
				<th>Descrição</th>
				<th>Status</th>
				<th></th>
			</tr>

		</thead>
		<tbody>
			<% if @requests.any? %>
			<% @requests.each do |request| %>
			<tr class="list-users">
				<td><%=request.id %></td>
				<td><%=request.description %></td>
				<td><%=request.status %></td>
				<td>
					<div class="btn-group">
						<a class="btn btn-mini dropdown-toggle" data-toggle="dropdown" href="#">Actions <span class="caret"></span></a>
						<ul class="dropdown-menu">
							<li><%=link_to fa_icon("pencil")+" Editar", client_edit_request_path(request)%></li>

							<li><%=link_to fa_icon("trash-o")+" Deletar", request, :method => :delete, :confirm => "Você tem certeza?" %></li>
							<li><%=link_to fa_icon("user")+" Detalhes", request %></li>
						</ul>
					</div>
				</td>

			</tr>
			<% end %>

			<% else %>
			<div class="alert">
				<%=link_to "Nova Requisicao", new_client_request_path, :class => "btn btn-primary" %>
			</div>
			<% end %>
		</tbody>
	</table>	
	</div>
</div>

app/views/requests/update.js.erb
<% if @request.persisted? %>
$("#requisicao").html("<%=j render :partial => 'requests/index', :locals => {:requests => @request.client.requests} %>");
$("#requisicao").prepend("<%=j notice %>")
$("#nova_resisicao").html("<%=j render :partial => 'requests/form', :locals => {:request => Request.new, :client => @request.client} %>");
<% else %>
$("#requisicao").html("<%=j render :partila => 'request/form', :locals => {:request => @request, :client => @request.client} %>");

app/views/shared/_menu_top.html.erb
<div class="navbar navbar-fixed-top">
      <div class="navbar-inner">
        <div class="container-fluid">
          <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </a>
          <a class="brand" href="#">Control Request</a>
          <div class="btn-group pull-right">
			<a class="btn" href="#"><i class="icon-user"></i> Admin</a>
            <a class="btn dropdown-toggle" data-toggle="dropdown" href="#">
              <span class="caret"></span>
            </a>
            <ul class="dropdown-menu">
			  <li><a href="#">Profile</a></li>
              <li class="divider"></li>
              <li><a href="#">Logout</a></li>
            </ul>
          </div>
          <div class="nav-collapse">
            <ul class="nav">
      <li><%=link_to "Home", root_path %></li>
              <li class="dropdown"><a href="#" class="dropdown-toggle" data-toggle="dropdown">Users <b class="caret"></b></a>
        <ul class="dropdown-menu">
          <li><a href="new-user.html">New User</a></li>
          <li class="divider"></li>
          <li><a href="users.html">Manage Users</a></li>
        </ul>
        </li>
              <li class="dropdown"><a href="#" class="dropdown-toggle" data-toggle="dropdown">Clientes<b class="caret"></b></a>
        <ul class="dropdown-menu">
          <li><%=link_to "Novo Cliente", new_client_path %></li>
          <li class="divider"></li>
          <li><%=link_to "Listar clientes", clients_path %></li>
        </ul>
        </li>
        <li><a href="stats.html">Stats</a></li>
            </ul>
          </div>
        </div>
      </div>
    </div>

app/views/shared/_sidebar.html.erb
<div class="span3">
  <div class="well sidebar-nav">
    <ul class="nav nav-list">
      <li class="nav-header"><i class="icon-wrench"></i> Administration</li>
      <li class="active"><a href="users.html">Users</a></li>
      <li><a href="roles.html">Roles</a></li>
      <li class="nav-header"><i class="icon-signal"></i> Statistics</li>
      <li><a href="stats.html">General</a></li>
      <li><a href="user-stats.html">Users</a></li>
      <li><a href="visitor-stats.html">Visitors</a></li>
      <li class="nav-header"><i class="icon-user"></i> Profile</li>
      <li><a href="my-profile.html">My profile</a></li>
      <li><a href="#">Settings</a></li>
      <li><a href="#">Logout</a></li> 
    </ul>
  </div>
</div>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :login %><br>
    <%= f.text_field :login %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<h1>Listing users</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th>Login</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.name %></td>
        <td><%= user.email %></td>
        <td><%= user.login %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New user</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @user.name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>

<p>
  <strong>Login:</strong>
  <%= @user.login %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>

app/views/welcome/index.html.erb
<div>
	<%=link_to "Clientes", clients_path, :class => "btn btn-success btn-large" %>
</div>